server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task-management
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog.yaml
    default-schema: public

jwt:
  secret: "secure_secret_key"
  expiration: 3600000 # 1 час в миллисекундах